### ISSUE TITLE
Could you please add instructions on how to set up portainer 8000 port?

### ISSUE THREAD

**Issue by lchen198** [rafrasenberg/docker-traefik-portainer#1]
I am trying to enable edge computing in portainer, which requires to open up port 8000. Based on the instruction in the edge agent page in portainer, I need to expose portainer.mydomain.com:8000.

I tried to add edge.mydomain.com to your portainer docker config based on the instruction here https://documentation.portainer.io/v2.0/ad/traefik/rp-traefik/

However, I was not able to get it running. Traefik complained about not able to get https working in the edge domain. It is also not clear to me how to let an edge agent connecting to the edge.mydomain.com.

How should I 1) expose port 8000 from portainer? 2) redirect portainer.mydomain.com:8000 to portainer? 

Thanks a lot!

**Comment by rafrasenberg** [comment]
Closing this as a won't fix, since it's been too long ago.
